project:
  type: book

book:
  title: "Autism All Grown Up"
  subtitle: "The Autism Nexus of Oregon"
  author: "Ariel Balter"
  date: now
  chapters:
    - index.qmd
    - mission.qmd
    - executive_summary.qmd
    - lost_generations.qmd
    - autism_all_grown_up.qmd
    - funding.qmd
    - budget3.qmd
  appendices:
    - specific_issues.qmd
    - glossary3.qmd
    - representitive_salaries.qmd
    - potential_funders2.qmd
    - neurodiversity_and_neurodivergence.qmd
  references: references.qmd

  sidebar:
    tools:
      - icon: file-earmark-pdf
        href: Autism-All-Grown-Up.pdf
      - icon: file-earmark-word
        href: Autism-All-Grown-Up.docx
    collapse-level: 4

bibliography: aagu.bib

format:
  html:
    theme: yeti
    output-dir: docs
    number-sections: true
    toc: true
    number-depth: 2
  pdf:
    documentclass: scrreprt
    number-sections: true
    number-depth: 1
    toc-title: "Contents"
    toc: true
    toc-depth: 2
  docx:
    number-sections: true
    number-depth: 1
    toc-title: "Contents"
    toc: true
    toc-depth: 2

editor: visual
